#version: "3.9"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5418:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./docker-entrypoint.sh:/docker-entrypoint-override.sh
    entrypoint: [ "/bin/bash", "/docker-entrypoint-override.sh" ]
    command: >
      postgres -c shared_preload_libraries=timescaledb

volumes:
  timescale_data:
    name: timescale_data